#!/usr/bin/env python3
"""Front-wheel fix variants: test cars that each try a fix for the front
wheels' judder / wobble in hard corners (round 12).

    python3 tools/rb14/variants.py            (after f1_setup.py)

Writes vehicles/redbull/fix_<n>.pc with info_fix_<n>.json (the name shown
in the game's vehicle selector, "Front Fix N · ...") and a labelled
thumbnail, plus plans/front-fixes.md, the test sheet. Each changes only the
front-fix tuning variables (f1_setup.FRONT_FIX_VARS) or the front dampers
from Baseline. They are ordered safest first: every car is run through the
same checks as the main configs, and the ones that go over a limit say so
in their description (they may break at spawn -- that's the point of
trying several). build_mod.py --no-variants leaves them out.
"""
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
import setup_report as sr  # noqa: E402
import f1_setup as fs  # noqa: E402

V = "vehicles/redbull"


def variants(b):
    """(title, what it tries, {vars}) from the Baseline vars b."""
    return [
        ("Stiffer tyres", "front tire carcass 1.3x -- less tyre squirm; inside every limit",
         {"$tyre_carcass_F": 1.3}),
        ("Much stiffer tyres", "front tire carcass 1.6x (0.85x the F4's stiffness per kg); inside every limit",
         {"$tyre_carcass_F": 1.6}),
        ("Stiff tyres + wheel-hop dampers", "carcass 1.3x and the front dampers 40 % firmer (bump / rebound), "
         "to hold the wheel against hop; the dampers are low-pass filtered, which the offline check can't see",
         {"$tyre_carcass_F": 1.3, "$damp_bump_F": round(b["$damp_bump_F"] * 1.4),
          "$damp_rebound_F": round(b["$damp_rebound_F"] * 1.4)}),
        ("Stiff tyres + heavier uprights", "carcass 1.3x and 2 kg per corner moved from the rim to the "
         "upright -- RISKIER: puts the rims just over the stiffness target",
         {"$tyre_carcass_F": 1.3, "$upright_mass_F": 2}),
        ("Much stiffer tyres + upright damping", "carcass 1.6x and front upright damping 800 (round 11 broke "
         "at 900) -- RISKIEST: over the wheel-corner damping limit",
         {"$tyre_carcass_F": 1.6, "$carrier_damp_F": 800}),
    ]


def gates(v):
    st = sr.stability_report(v, top=400)
    corner = max((float(m.split(":")[0]) for m in st["damped_modes"]
                  if any(k in m.split(":")[1].split(",")[0] for k in fs.CORNER_NODES)), default=0.0)
    ref = {r["name"][0]: r for r in sr.Vehicle("fr04", None).wheels()}
    tyre = 0.0
    for r in v.wheels():
        f4 = ref[r["name"][0]]
        for key in fs.TYRE_SPRINGS:
            tyre = max(tyre, (v.val(r.get(key)) / v.val(r.get("nodeWeight"))) /
                       (v.val(f4.get(key)) / v.val(f4.get("nodeWeight"))))
    mr = sr.mass_report(v)
    v._yf, v._yr = mr["yf"], mr["yr"]
    aero, _ = sr.aero_report(v)
    strength = sr.strength_report(v, mr, aero)[0][0]
    hits = sr.wheel_clearance(v, fs.WHEEL_CLEARANCE)
    over = []
    if st["max"] > fs.MAX_OMEGA_DT:
        over.append("stiffness %.2f > %.2f" % (st["max"], fs.MAX_OMEGA_DT))
    if st["damped"] > fs.MAX_DAMPED:
        over.append("damping %.2f > %.2f" % (st["damped"], fs.MAX_DAMPED))
    if corner > fs.MAX_DAMPED_CORNER + 1e-9:
        over.append("wheel-corner damping %.2f > %.2f" % (corner, fs.MAX_DAMPED_CORNER))
    if tyre > fs.TYRE_MAX_K_PER_KG + 1e-6:
        over.append("tyres %.2f x the F4's per kg" % tyre)
    if strength > fs.STRENGTH_MAX_RATIO:
        over.append("strength %.2f" % strength)
    if hits:
        over.append("wheel clearance")
    if st["max"] >= 2 or st["damped"] >= 2:
        raise SystemExit("variant over the hard solver limit (2): would certainly break")
    return dict(stiff=st["max"], damped=st["damped"], corner=corner, tyre=tyre, strength=strength, over=over)


def thumbnail(label, path):
    subprocess.run(["convert", f"{V}/baseline.jpg", "-gravity", "South", "-fill", "white",
                    "-undercolor", "#000000B0", "-font", "DejaVu-Sans-Bold", "-pointsize", "40",
                    "-annotate", "+0+24", f" {label} ", "-quality", "85", path], check=True)


def main():
    os.chdir(REPO)
    for f in glob.glob(f"{V}/fix_*") + glob.glob(f"{V}/info_fix_*"):
        os.remove(f)
    base = json.load(open(f"{V}/baseline.pc"))
    base_info = json.load(open(f"{V}/info_baseline.json"))
    bv = {k: float(x) for k, x in base["vars"].items()}
    sheet = ["# Front-wheel fix variants", "",
             "Test cars generated by `tools/rb14/variants.py` (round 12): each tries a fix for",
             "the front wheels' judder / wobble in hard corners (and the front wing shaking",
             "with them). Everything else is **Baseline**. In the game they are in the RB14's",
             "configuration list as *Front Fix N · ...*, safest first; the later ones go over",
             "an offline limit on purpose and may break at spawn. Note for each: does it",
             "spawn cleanly, and how the front feels in a hard corner.", "",
             "Offline checks: stiffness = highest omega*dt (target <= %.2f), damped = with"
             % fs.MAX_OMEGA_DT,
             "damping (<= %.2f), corner = wheel-corner modes with damping (<= %.2f; round 10"
             % (fs.MAX_DAMPED, fs.MAX_DAMPED_CORNER),
             "was 1.78 and fine, round 11 1.83 and broke), tyres = stiffness per kg vs the F4's (<= 1).", "",
             "| Car | Tries | stiffness | damped | corner | tyres | spawns? | judder? |",
             "|---|---|---|---|---|---|---|---|"]
    for n, (title, tries, over) in enumerate(variants(bv), 1):
        name = f"fix_{n}"
        vars_ = dict(base["vars"])
        vars_.update(over)
        pc = {**base, "vars": {k: vars_[k] for k in sorted(vars_)}}
        with open(f"{V}/{name}.pc", "w", newline="\n") as fh:
            json.dump(pc, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        g = gates(sr.Vehicle("redbull", name))
        risk = ("Passes every offline check." if not g["over"] else
                "Over an offline limit (%s): may break at spawn." % "; ".join(g["over"]))
        ui = f"Front Fix {n} · {title}"
        changed = ", ".join(f"{k.lstrip('$')} {x:g}" for k, x in over.items())
        desc = f"Front-wheel fix test car {n}: {tries}. Everything else is Baseline ({changed}). {risk}"
        info = {**base_info, "Config Type": "Custom", "Configuration": ui, "Description": desc}
        with open(f"{V}/info_{name}.json", "w", newline="\n") as fh:
            json.dump(info, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        thumbnail(ui, f"{V}/{name}.jpg")
        sheet.append(f"| `{name}` {title} | {tries} | {g['stiff']:.2f} | {g['damped']:.2f} | {g['corner']:.2f} | "
                     f"{g['tyre']:.2f} | | |")
        print(f"{ui:48s} stiffness {g['stiff']:.2f} damped {g['damped']:.2f} corner {g['corner']:.2f} "
              f"tyres {g['tyre']:.2f} strength {g['strength']:.2f}  {'OK' if not g['over'] else 'OVER: ' + '; '.join(g['over'])}")
    with open("plans/front-fixes.md", "w") as fh:
        fh.write("\n".join(sheet) + "\n")
    print("front-fix variants written; test sheet plans/front-fixes.md")


if __name__ == "__main__":
    main()
